language: go

go:
 - 1.15.x
env:
 - GO111MODULE=on

dist: trusty

install:
  - go get -v -t -d ./...
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - go test -race -v .
  - golangci-lint run -E gofmt -E goimports -E misspell -E ineffassign -E staticcheck -E gosimple -D errcheck
